### ISSUE TITLE
Docs for Haystack Hub

### ISSUE THREAD

**Issue by PiffPaffM** [deepset-ai/haystack-website#17]
As a user, I want to know how to use Haystack Hub in detail so that I can use it more efficient.

**Comment by brandenchan** [comment]
- Currently the landing page is the free trial section. I think I would rather have a ToC as a landing page, perhaps with a smaller banner advertising free trial period. This would be more navigable by non-first time Hub users

- I think it would be better if `Free Trial` and `Quickstart` were separate pages

- In the `Quickstart` page, I think it looks neater if the titles read "Step 1: Choose Workspace Language" instead of "Step 1 Choose Workspace Language"

- The link in `Quickstart`->Step 3 Configure Model doesn't work

- In `Configure Workspace`, the first sentence needs to be rephrased `"Your organization a one workspace which needs to be configured before you can start to search."`

- `Upload Documents` Let's chang the first sentence to be gender neutral `"In Haystack Hub, the user can upload documents which THEY would like to search"`

- `Configure Model` Reader refers to the model as "deepset/ert-base-cased-squad2"

- `Configure Model` No answer boost section refers to noanswer, "no answer", "noanswer" and "no_answer". Let's choose one way of writing it

- `Configure Model` Default Top-K section missing a final "R". `"How many answers to extract for each candidate doc that is coming from the retrieveR."`

- `Configure Model` Doc Stride missing a bracket `"Length of striding window for splitting long texts (used if len(text) > maxseqlen."`

- `User Settings` there are about 5 places on this page where we can refer to the user in a gender neutral way

-`Rest API-Introduction` is misspelled

- `Rest API -Introduction` I think it would give a better impression if this page wasn't just error codes. Is there any info that would give an intro to the Rest API? I.e. how to call or default connection ports?
